
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass brutelogin
      --maxmemory 4096mb
      --maxmemory-policy allkeys-lru
      --appendonly yes


volumes:
  redis_data:
